### PR TITLE
fixed: python3.5 open notebook throw exception

### PR DESCRIPTION
**Pull request by xuande**
In python3.5 open notebook throw TypeError("the JSON object must be str, not 'bytes'",)

### CODE REVIEW

**Review by jimdowling — COMMENTED** [review]
Is this compatible with 2.7?

**Comment by xuande** [comment]
@jimdowling Yes, it's compatible with  python2.7

**Comment by alshishtawy** [comment]
We depend on pydoop. Currently, pydoop requires Python 2.7. Python 3 support is in their [future work](https://crs4.github.io/pydoop/ideas_list.html#python-3-porting).

How did you manage to run pydoop in Python 3.5?

I'm asking because read() should [return string](https://github.com/crs4/pydoop/blob/5d278af4a306b0daff360879d62e78f0a2e1c8c3/pydoop/hdfs/file.py#L247) not bytes. Did you use automatic conversion to port 2to3?

**Comment by xuande** [comment]
@alshishtawy Pydoop has a `develop-py3` branch https://github.com/crs4/pydoop/tree/develop-py3

**Comment by alshishtawy** [comment]
@xuande Thanks for pointing that out! That explains it as now they are returning bytes 

return b"".join(chunks)

The develop-py3 is two years old but more interestingly is that just 7 hrs ago there is a [PR](https://github.com/crs4/pydoop/pull/232) to update it :) I'll wait a bit to see how that goes.

**Comment by lucasdurand** [comment]
How'd it go???

**Pull request closed without merging**
